### ISSUE TITLE
Feedback homework week 2

### ISSUE THREAD

**Issue by remarcmij** [jamsrahimi/hyf-javascript1#1]
Hi Jams, here is my feedback on your homework.

exercise 3

- Just a tip: if you use double quotes to define a string you do not need to escape single quotes within that string. And vice versa. For instance:

```js
console.log("The value of x will be: \"Integer value '179' as defined\"");
```

exercise 5

- In line 10, there should normally be a space after a comma in a parameter list. If you added the correct settings in VSCode this should happen automatically as you type. Can you check your settings as listed here in [VSCode Tips](https://github.com/HackYourFuture/JavaScript/tree/master/VSCodeTips#customise-vscode-settings)?

exercise 6

- You _can_ say that the array is empty but it is not `undefined`.
- I like your use of `const` here. I prefer to use `const` over `let` whenever I can.
- Make sure that you are consistent in your use of upper- and lowercase. In your case, when you have `"Bat"` and `"Dinosaur"` I would also expect `"Baby Pig"`.
- Make sure to add a space following a comma in your array definitions. Again, this should happen automatically if you have the right settings in VSCode.

exercise 7

- I note your marital status is not a `const` :grin:
- You will have noticed that `typeof` an array is actually `object` and not `array`. An array is regarded as a special type of object.

execise 8

- I see you were having some fun with arrays. But when you compare two values make sure that you use the triple form `===`.

Despite your 'procrastination' you've done an excellent job. You seem to have a good grasp of the concepts and your code is well-formatted and well organised. Well done!

**Comment by jamsrahimi** [comment]
Thank you Jim, I have already fixed the issue right away. The times of such comprehensive and beautiful comments are over, I hope I get such comments in future, but first I have to do my homework on time. I am closing the issue now.
